# 숫자 & 범주형 데이터의 이해_17강

In [4]:
import pandas as pd

In [5]:
stock_data=pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets%2F4538%2F7213%2FETFs%2Facim.us.txt?GoogleAccessId=gcp-kaggle-com@kaggle-161607.iam.gserviceaccount.com&Expires=1594647728&Signature=lFmeWp48YnNV2GyhC0CHblaB%2FU7O1KC3HhLSNKWc1ZSfU45%2F21oD8PXDDVJ%2BmPZ92H1B7NqZ75r6QJtFl1ULj9UKAQl6%2BArz%2B%2F73o6rADXQpate3OTeN9L8SQHGFU3C6Y6cJ6a2yH1NFRWCtxU6DArlbDjAsE93iR75nsIJv9HHqoAnwhr3RpLhaQHFcyXuGZ8JYq%2FwIYvYESp%2BiaOeFLjFoOUpvQ43FycRyDBsQbdpm8qM8W20%2Fk0Oqax9d7RSj0GyYUI8FWDaTiUjjJllZSrUZG1fA5GeqO2w96BzindI26ALkulQWdQgQ6gXBY8n431gJmCNVM6xSo9vcDPUYhw%3D%3D')
stock_data.head()

         Date    Open    High     Low   Close  Volume  OpenInt
0  2012-03-06  43.011  43.011  43.011  43.011     509        0
1  2012-03-07  43.162  43.162  43.162  43.162     113        0
2  2012-03-08  43.956  43.956  43.956  43.956     227        0
3  2012-03-12  43.885  43.885  43.885  43.885    1248        0
4  2012-03-13  45.880  45.880  44.555  44.555     227        0

**info 함수로 각 변수의 데이터 타입 확인**
~~~
타입 변경을 astype 함수를 사용
~~~

In [6]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     1232 non-null   object
 1   Open     1232 non-null   float64
 2   High     1232 non-null   float64
 3   Low      1232 non-null   float64
 4   Close    1232 non-null   float64
 5   Volume   1232 non-null   int64
 6   OpenInt  1232 non-null   int64
dtypes: float64(4), int64(2), object(1)
memory usage: 67.5+ KB

**숫자형(Numerical Type) 데이터**
~~~
연속성을 띄는 숫자로 이루어진 data
    예) age, Fare 등
    ~~~

**범주형(Catagorical Type) 데이터**
~~~
연속적이지 않은 값(대부분의 경우 숫자를 제외한 나머지 값)을 갖는 데이터 의미
    예) Name, Sex, Ticket, Cabin, Embarked
어떤 경우, 숫자형 타입이라 할 지라도 개념적으로 범주형으로 처리해야 할 경우가 있음
    예) Pclass
    ~~~
범주형 데이터는 값을 처리할 수 없으므로 없애거나 숫자형으로 바꾸어 데이터 처리

In [7]:
type(stock_data['Volume'])

pandas.core.series.Series

# 숫자형 데이터의 범주형 데이터화_18강

**astype 사용하여 간단하게 타입만 변화**
~~~
숫자형 type을 범주형으로 변화
~~~

In [8]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     1232 non-null   object
 1   Open     1232 non-null   float64
 2   High     1232 non-null   float64
 3   Low      1232 non-null   float64
 4   Close    1232 non-null   float64
 5   Volume   1232 non-null   int64
 6   OpenInt  1232 non-null   int64
dtypes: float64(4), int64(2), object(1)
memory usage: 67.5+ KB

In [9]:
stock_data['Volume']=stock_data['Volume'].astype(str)   #type를 바꾸는데 사용

In [10]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     1232 non-null   object
 1   Open     1232 non-null   float64
 2   High     1232 non-null   float64
 3   Low      1232 non-null   float64
 4   Close    1232 non-null   float64
 5   Volume   1232 non-null   object
 6   OpenInt  1232 non-null   int64
dtypes: float64(4), int64(1), object(2)
memory usage: 67.5+ KB

**변환 로직을 함수로 만들고 apply 함수로 적용**
~~~
숫자형 type을

In [11]:
import math

In [12]:
def open_catagorize(open):
    if math.isnan(open):
        return -1
    return math.floor(open/2)*2   #(open/10)*10는 일의 자리수를 삭제함

In [13]:
stock_data['Open'].apply(open_catagorize)   #(open/2)*2 는 모두 짝수로 변환

0       42
1       42
2       42
3       42
4       44
        ..
1227    76
1228    76
1229    76
1230    76
1231    76
Name: Open, Length: 1232, dtype: int64

# 범주형 데이터 잔처리 하기 (one-hot encoding)

**One-hot encoding**
~~~
범주형 데이터는 분석단계에서 계산이 어렵기 때문에 숫자형으로 변경이 필요
범주형 데이터의 각 번주(catagory)를 column 레벨로 변경
해당 범주에 포함되면, 1아니면 0으로 채우는 인코딩 기법
pandas.get_dummies 함수 사용
    drop_first: 첫번째 카테고리 값은 사용하지 않음
    ~~~

In [14]:
pd.get_dummies(stock_data)

,Open,High,Low,Close,OpenInt,Date_2012-03-06,Date_2012-03-07,Date_2012-03-08,Date_2012-03-12,Date_2012-03-13,...,Volume_9820,Volume_9856,Volume_9857,Volume_990,Volume_9910,Volume_994,Volume_9957,Volume_996,Volume_9962,Volume_997
0,43.0110,43.0110,43.011,43.0110,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,43.1620,43.1620,43.162,43.1620,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,43.9560,43.9560,43.956,43.9560,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,43.8850,43.8850,43.885,43.8850,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,45.8800,45.8800,44.555,44.5550,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,77.2700,77.2775,77.270,77.2775,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1228,77.5026,77.5026,77.200,77.3520,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1229,77.3700,77.7200,77.138,77.7200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1230,77.1300,77.1310,76.606,77.1100,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1231,76.5500,76.9000,76.550,76.9000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
pd.get_dummies(stock_data,columns=['High','Low'])   #각 High와 Low값이 column level로 올라간다

,Date,Open,Close,Volume,OpenInt,High_39.579,High_40.258,High_40.356,High_40.409,High_40.411,...,Low_76.57,Low_76.5856,Low_76.596,Low_76.60600000000001,Low_77.0352,Low_77.0512,Low_77.0732,Low_77.138,Low_77.2,Low_77.27
0,2012-03-06,43.0110,43.0110,509,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2012-03-07,43.1620,43.1620,113,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2012-03-08,43.9560,43.9560,227,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2012-03-12,43.8850,43.8850,1248,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2012-03-13,45.8800,44.5550,227,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,2017-11-06,77.2700,77.2775,533,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1228,2017-11-07,77.5026,77.3520,12471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1229,2017-11-08,77.3700,77.7200,13482,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1230,2017-11-09,77.1300,77.1100,4038,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1231,2017-11-10,76.5500,76.9000,6361,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
pd.get_dummies(stock_data,columns=['High','Low'],drop_first=True)   #하나의 column을 없앰
                                                     #나머지의 정보들로 없어진 정보 충분히 유추 가능

,Date,Open,Close,Volume,OpenInt,High_40.258,High_40.356,High_40.409,High_40.411,High_40.62,...,Low_76.57,Low_76.5856,Low_76.596,Low_76.60600000000001,Low_77.0352,Low_77.0512,Low_77.0732,Low_77.138,Low_77.2,Low_77.27
0,2012-03-06,43.0110,43.0110,509,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2012-03-07,43.1620,43.1620,113,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2012-03-08,43.9560,43.9560,227,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2012-03-12,43.8850,43.8850,1248,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2012-03-13,45.8800,44.5550,227,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,2017-11-06,77.2700,77.2775,533,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1228,2017-11-07,77.5026,77.3520,12471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1229,2017-11-08,77.3700,77.7200,13482,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1230,2017-11-09,77.1300,77.1100,4038,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1231,2017-11-10,76.5500,76.9000,6361,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# DataFrame group by 이해하기

**SQL의 group by와 개념적으로 동일하디**

In [17]:
stock_data.head()

         Date    Open    High     Low   Close Volume  OpenInt
0  2012-03-06  43.011  43.011  43.011  43.011    509        0
1  2012-03-07  43.162  43.162  43.162  43.162    113        0
2  2012-03-08  43.956  43.956  43.956  43.956    227        0
3  2012-03-12  43.885  43.885  43.885  43.885   1248        0
4  2012-03-13  45.880  45.880  44.555  44.555    227        0

**GroupBy group 속성**
~~~
각 그룹과 그룹에 속한 index를 dict 형태로 표현
~~~

In [18]:
class_group=stock_data.groupby('Volume')
class_group

In [19]:
class_group.groups   #value에 해당하는 것은 key에 해당하는 index값들이

{'10038': Int64Index([293], dtype='int64'),
 '1007': Int64Index([852], dtype='int64'),
 '1009': Int64Index([47, 49, 53, 54, 57, 61, 62, 63], dtype='int64'),
 '10105': Int64Index([950], dtype='int64'),
 '1011': Int64Index([970], dtype='int64'),
 '1012': Int64Index([458], dtype='int64'),
 '10137': Int64Index([675], dtype='int64'),
 '1018': Int64Index([453], dtype='int64'),
 '10228': Int64Index([761], dtype='int64'),
 '1026': Int64Index([805], dtype='int64'),
 '1028': Int64Index([983], dtype='int64'),
 '1029': Int64Index([1157], dtype='int64'),
 '1030': Int64Index([204], dtype='int64'),
 '1033': Int64Index([177], dtype='int64'),
 '10346': Int64Index([706], dtype='int64'),
 '1035': Int64Index([279], dtype='int64'),
 '10351': Int64Index([468], dtype='int64'),
 '10372': Int64Index([911], dtype='int64'),
 '1041': Int64Index([346], dtype='int64'),
 '10420': Int64Index([1165], dtype='int64'),
 '1045': Int64Index([262, 633, 729], dtype='int64'),
 '105': Int64Index([680], dtype='int64'),
 '1051': Int64Index([910], dtype='int64'),
 '10528': Int64Index([77], dtype='int64'),
 '1055': Int64Index([1007, 1146], dtype='int64'),
 '1060': Int64Index([834], dtype='int64'),
 '1062': Int64Index([1130], dtype='int64'),
 '10625': Int64Index([1059], dtype='int64'),
 '1064': Int64Index([555, 580, 602, 619], dtype='int64'),
 '10656': Int64Index([490], dtype='int64'),
 '1068': Int64Index([196], dtype='int64'),
 '10681': Int64Index([763], dtype='int64'),
 '107': Int64Index([623], dtype='int64'),
 '1073': Int64Index([320], dtype='int64'),
 '10739': Int64Index([499], dtype='int64'),
 '10764': Int64Index([711], dtype='int64'),
 '1079': Int64Index([1132], dtype='int64'),
 '108': Int64Index([399], dtype='int64'),
 '1081': Int64Index([136], dtype='int64'),
 '1085': Int64Index([1224], dtype='int64'),
 '1089': Int64Index([496, 1204], dtype='int64'),
 '109': Int64Index([345], dtype='int64'),
 '1092': Int64Index([274], dtype='int64'),
 '1099': Int64Index([1163], dtype='int64'),
 '110': Int64Index([182, 185, 189, 200, 206, 213, 221, 227, 234, 248, 251, 258], dtype='int64'),
 '1100': Int64Index([477], dtype='int64'),
 '1103': Int64Index([341], dtype='int64'),
 '11036': Int64Index([1035], dtype='int64'),
 '1106': Int64Index([86, 128, 174], dtype='int64'),
 '11077': Int64Index([659], dtype='int64'),
 '1108': Int64Index([806], dtype='int64'),
 '111': Int64Index([95, 108, 114, 129, 130, 147], dtype='int64'),
 '1110': Int64Index([452], dtype='int64'),
 '1113': Int64Index([445], dtype='int64'),
 '1115': Int64Index([478], dtype='int64'),
 '1116': Int64Index([312], dtype='int64'),
 '11184': Int64Index([164], dtype='int64'),
 '112': Int64Index([29, 40], dtype='int64'),
 '1120': Int64Index([28, 30, 31], dtype='int64'),
 '112074': Int64Index([577], dtype='int64'),
 '11215': Int64Index([883], dtype='int64'),
 '113': Int64Index([1, 7, 8], dtype='int64'),
 '1131': Int64Index([319], dtype='int64'),
 '11322': Int64Index([783], dtype='int64'),
 '1135': Int64Index([5, 18, 1128], dtype='int64'),
 '11378': Int64Index([613], dtype='int64'),
 '1139': Int64Index([321], dtype='int64'),
 '11400': Int64Index([1025], dtype='int64'),
 '1149': Int64Index([642, 652], dtype='int64'),
 '1151': Int64Index([528], dtype='int64'),
 '11636': Int64Index([1058], dtype='int64'),
 '1165': Int64Index([601], dtype='int64'),
 '11661': Int64Index([79], dtype='int64'),
 '11686': Int64Index([523], dtype='int64'),
 '11692': Int64Index([1098], dtype='int64'),
 '1171': Int64Index([796], dtype='int64'),
 '11723': Int64Index([1174], dtype='int64'),
 '118': Int64Index([208], dtype='int64'),
 '11803': Int64Index([575], dtype='int64'),
 '1182': Int64Index([363], dtype='int64'),
 '1189': Int64Index([329], dtype='int64'),
 '1192': Int64Index([471], dtype='int64'),
 '1200': Int64Index([835], dtype='int64'),
 '1201': Int64Index([1155], dtype='int64'),
 '12016': Int64Index([599], dtype='int64'),
 '1202': Int64Index([187, 195, 231], dtype='int64'),
 '1205': Int64Index([1216], dtype='int64'),
 '1206': Int64Index([773, 848], dtype='int64'),
 '1209': Int64Index([469], dtype='int64'),
 '12144': Int64Index([503], dtype='int64'),
 '12155': Int64Index([1178], dtype='int64'),
 '1220': Int64Index([909], dtype='int64'),
 '1221': Int64Index([645], dtype='int64'),
 '12222': Int64Index([702], dtype='int64'),
 '1226': Int64Index([949, 1222], dtype='int64'),
 '1227': Int64Index([843], dtype='int64'),
 '1232': Int64Index([36, 66, 70], dtype='int64'),
 '1238': Int64Index([772], dtype='int64'),
 '1241': Int64Index([1199], dtype='int64'),
 '1242': Int64Index([921], dtype='int64'),
 '1243': Int64Index([757], dtype='int64'),
 '12437': Int64Index([1030], dtype='int64'),
 '12438': Int64Index([792], dtype='int64'),
 '12471': Int64Index([1228], dtype='int64'),
 '1248': Int64Index([3], dtype='int64'),
 '1252': Int64Index([1219], dtype='int64'),
 '1254': Int64Index([638, 641, 650, 710, 749, 1160], dtype='int64'),
 '1256': Int64Index([369, 377], dtype='int64'),
 '1261': Int64Index([429], dtype='int64'),
 '12621': Int64Index([548], dtype='int64'),
 '12623': Int64Index([159], dtype='int64'),
 '1264': Int64Index([1039], dtype='int64'),
 '1265': Int64Index([855], dtype='int64'),
 '12652': Int64Index([52], dtype='int64'),
 '1266': Int64Index([406], dtype='int64'),
 '1271': Int64Index([1211], dtype='int64'),
 '1274': Int64Index([1129], dtype='int64'),
 '12741': Int64Index([760], dtype='int64'),
 '12749': Int64Index([674], dtype='int64'),
 '1276': Int64Index([554], dtype='int64'),
 '1279': Int64Index([381, 541], dtype='int64'),
 '1281': Int64Index([488], dtype='int64'),
 '12854': Int64Index([734], dtype='int64'),
 '12938': Int64Index([32], dtype='int64'),
 '1296': Int64Index([766], dtype='int64'),
 '1297': Int64Index([287], dtype='int64'),
 '12974': Int64Index([610], dtype='int64'),
 '130363': Int64Index([574], dtype='int64'),
 '1304': Int64Index([105, 894], dtype='int64'),
 '13051': Int64Index([1011], dtype='int64'),
 '1308': Int64Index([455], dtype='int64'),
 '130999': Int64Index([573], dtype='int64'),
 '1311': Int64Index([220, 240, 890], dtype='int64'),
 '1313': Int64Index([481], dtype='int64'),
 '1316': Int64Index([410, 421], dtype='int64'),
 '1322': Int64Index([380], dtype='int64'),
 '1325': Int64Index([273], dtype='int64'),
 '13253': Int64Index([605], dtype='int64'),
 '1328': Int64Index([889], dtype='int64'),
 '1329': Int64Index([111, 138], dtype='int64'),
 '13295': Int64Index([816], dtype='int64'),
 '1330': Int64Index([1154], dtype='int64'),
 '13307': Int64Index([1090], dtype='int64'),
 '1334': Int64Index([85], dtype='int64'),
 '13354': Int64Index([998], dtype='int64'),
 '134': Int64Index([168], dtype='int64'),
 '1340': Int64Index([893], dtype='int64'),
 '1346': Int64Index([301], dtype='int64'),
 '13482': Int64Index([1229], dtype='int64'),
 '1349': Int64Index([364], dtype='int64'),
 '136528': Int64Index([579], dtype='int64'),
 '1368': Int64Index([975], dtype='int64'),
 '1377': Int64Index([44], dtype='int64'),
 '1378': Int64Index([1106], dtype='int64'),
 '138': Int64Index([394], dtype='int64'),
 '1383': Int64Index([328, 558, 560, 563], dtype='int64'),
 '13835': Int64Index([283], dtype='int64'),
 '1386': Int64Index([370], dtype='int64'),
 '13883': Int64Index([1032], dtype='int64'),
 '13916': Int64Index([1027], dtype='int64'),
 '1394': Int64Index([186], dtype='int64'),
 '1395': Int64Index([139], dtype='int64'),
 '14003': Int64Index([672], dtype='int64'),
 '1402': Int64Index([465], dtype='int64'),
 '140941': Int64Index([901], dtype='int64'),
 '1411': Int64Index([501], dtype='int64'),
 '1417': Int64Index([929], dtype='int64'),
 '1421': Int64Index([412], dtype='int64'),
 '1423': Int64Index([1073], dtype='int64'),
 '1429': Int64Index([840], dtype='int64'),
 '1441': Int64Index([176], dtype='int64'),
 '14423': Int64Index([673], dtype='int64'),
 '1444': Int64Index([211], dtype='int64'),
 '1445': Int64Index([462], dtype='int64'),
 '144792': Int64Index([576], dtype='int64'),
 '1450': Int64Index([785], dtype='int64'),
 '1451': Int64Index([181], dtype='int64'),
 '1453': Int64Index([450], dtype='int64'),
 '1456': Int64Index([34, 661], dtype='int64'),
 '14593': Int64Index([165], dtype='int64'),
 '146': Int64Index([232], dtype='int64'),
 '1460': Int64Index([1175], dtype='int64'),
 '1463': Int64Index([684, 731], dtype='int64'),
 '14659': Int64Index([1074], dtype='int64'),
 '1471': Int64Index([1148], dtype='int64'),
 '1473': Int64Index([1206], dtype='int64'),
 '1476': Int64Index([280], dtype='int64'),
 '14766': Int64Index([1056], dtype='int64'),
 '1477': Int64Index([936], dtype='int64'),
 '1489': Int64Index([1226], dtype='int64'),
 '149': Int64Index([790], dtype='int64'),
 '1490': Int64Index([815], dtype='int64'),
 '1491': Int64Index([969], dtype='int64'),
 '1500': Int64Index([1161], dtype='int64'),
 '1507': Int64Index([194], dtype='int64'),
 '15111': Int64Index([1013], dtype='int64'),
 '1514': Int64Index([544], dtype='int64'),
 '1519': Int64Index([352], dtype='int64'),
 '15196': Int64Index([518], dtype='int64'),
 '1522': Int64Index([371], dtype='int64'),
 '1524': Int64Index([1156], dtype='int64'),
 '15271': Int64Index([1145], dtype='int64'),
 '1530': Int64Index([179, 225], dtype='int64'),
 '1532': Int64Index([865], dtype='int64'),
 '1536': Int64Index([1207], dtype='int64'),
 '1541': Int64Index([872], dtype='int64'),
 '1546': Int64Index([342], dtype='int64'),
 '1548': Int64Index([885], dtype='int64'),
 '15491': Int64Index([999], dtype='int64'),
 '1550': Int64Index([152], dtype='int64'),
 '1551': Int64Index([598], dtype='int64'),
 '15631': Int64Index([594], dtype='int64'),
 '1576': Int64Index([572], dtype='int64'),
 '1577': Int64Index([1209], dtype='int64'),
 '1585': Int64Index([314], dtype='int64'),
 '1591': Int64Index([621], dtype='int64'),
 '1592': Int64Index([378], dtype='int64'),
 '1599': Int64Index([259], dtype='int64'),
 '1618': Int64Index([209], dtype='int64'),
 '1629': Int64Index([1185], dtype='int64'),
 '163100': Int64Index([1034], dtype='int64'),
 '1636': Int64Index([873], dtype='int64'),
 '1639': Int64Index([192], dtype='int64'),
 '16408': Int64Index([666], dtype='int64'),
 '1641': Int64Index([539], dtype='int64'),
 '1643': Int64Index([1179], dtype='int64'),
 '1646': Int64Index([1122], dtype='int64'),
 '1647': Int64Index([191, 988], dtype='int64'),
 '166': Int64Index([83, 109], dtype='int64'),
 '1661': Int64Index([172], dtype='int64'),
 '1663': Int64Index([913], dtype='int64'),
 '1664': Int64Index([393], dtype='int64'),
 '1667': Int64Index([947], dtype='int64'),
 '1668': Int64Index([695], dtype='int64'),
 '1672': Int64Index([688], dtype='int64'),
 '16740': Int64Index([939], dtype='int64'),
 '16802': Int64Index([69], dtype='int64'),
 '1681': Int64Index([78, 80, 878], dtype='int64'),
 '16910': Int64Index([508], dtype='int64'),
 '1699': Int64Index([344], dtype='int64'),
 '1713': Int64Index([423, 1002], dtype='int64'),
 '1714': Int64Index([1048], dtype='int64'),
 '1718': Int64Index([786], dtype='int64'),
 '17205': Int64Index([997], dtype='int64'),
 '17230': Int64Index([1068], dtype='int64'),
 '1728': Int64Index([974], dtype='int64'),
 '1729': Int64Index([530], dtype='int64'),
 '1735': Int64Index([239], dtype='int64'),
 '1737': Int64Index([1083], dtype='int64'),
 '1738': Int64Index([1102], dtype='int64'),
 '1739': Int64Index([383], dtype='int64'),
 '1747': Int64Index([415], dtype='int64'),
 '17495': Int64Index([811], dtype='int64'),
 '1754': Int64Index([868], dtype='int64'),
 '17545': Int64Index([571], dtype='int64'),
 '1759': Int64Index([250, 916], dtype='int64'),
 '176': Int64Index([467], dtype='int64'),
 '1770': Int64Index([925], dtype='int64'),
 '1776': Int64Index([631, 634, 647, 655, 657, 718, 748], dtype='int64'),
 '1791': Int64Index([1126], dtype='int64'),
 '1792': Int64Index([1150], dtype='int64'),
 '1809': Int64Index([552, 592, 611], dtype='int64'),
 '1819': Int64Index([470, 1172], dtype='int64'),
 '1820': Int64Index([372], dtype='int64'),
 '1825': Int64Index([1200], dtype='int64'),
 '1828': Int64Index([384], dtype='int64'),
 '1846': Int64Index([832], dtype='int64'),
 '185': Int64Index([235], dtype='int64'),
 '1857': Int64Index([255], dtype='int64'),
 '18589': Int64Index([578], dtype='int64'),
 '186': Int64Index([376], dtype='int64'),
 '1860': Int64Index([270, 922], dtype='int64'),
 '1882': Int64Index([662], dtype='int64'),
 '1884': Int64Index([1208], dtype='int64'),
 '1893': Int64Index([242], dtype='int64'),
 '1900': Int64Index([943], dtype='int64'),
 '1905': Int64Index([59], dtype='int64'),
 '1906': Int64Index([433], dtype='int64'),
 '1909': Int64Index([375, 386], dtype='int64'),
 '191': Int64Index([253], dtype='int64'),
 '1916': Int64Index([615, 747], dtype='int64'),
 '1918': Int64Index([525], dtype='int64'),
 '19239': Int64Index([299], dtype='int64'),
 '1924': Int64Index([1195], dtype='int64'),
 '1927': Int64Index([222], dtype='int64'),
 '1934': Int64Index([403, 510], dtype='int64'),
 '1939': Int64Index([1089], dtype='int64'),
 '1943': Int64Index([793], dtype='int64'),
 '1944': Int64Index([347], dtype='int64'),
 '1947': Int64Index([788], dtype='int64'),
 '1955': Int64Index([532], dtype='int64'),
 '1965': Int64Index([1213], dtype='int64'),
 '1980': Int64Index([286], dtype='int64'),
 '1985': Int64Index([629, 726], dtype='int64'),
 '19856': Int64Index([654], dtype='int64'),
 '1993': Int64Index([169], dtype='int64'),
 '19976': Int64Index([1028], dtype='int64'),
 '2003': Int64Index([1131], dtype='int64'),
 '20124': Int64Index([1018], dtype='int64'),
 '2016': Int64Index([48, 50, 60], dtype='int64'),
 '2020': Int64Index([609], dtype='int64'),
 '2031': Int64Index([441], dtype='int64'),
 '2042': Int64Index([10], dtype='int64'),
 '2048': Int64Index([996, 1186], dtype='int64'),
 '2049': Int64Index([1218], dtype='int64'),
 '2056': Int64Index([963], dtype='int64'),
 '2058': Int64Index([1026], dtype='int64'),
 '20660': Int64Index([887], dtype='int64'),
 '20675': Int64Index([722], dtype='int64'),
 '2073': Int64Index([776], dtype='int64'),
 '2085': Int64Index([315], dtype='int64'),
 '2087': Int64Index([353, 1205], dtype='int64'),
 '209': Int64Index([628, 632, 686, 708, 721], dtype='int64'),
 '2090': Int64Index([679, 709, 746], dtype='int64'),
 '21047': Int64Index([276], dtype='int64'),
 '2106': Int64Index([1121], dtype='int64'),
 '2109': Int64Index([914], dtype='int64'),
 '21138': Int64Index([1171], dtype='int64'),
 '2122': Int64Index([800], dtype='int64'),
 '2123': Int64Index([1078], dtype='int64'),
 '2128': Int64Index([71], dtype='int64'),
 '213': Int64Index([339, 557, 626], dtype='int64'),
 '21300': Int64Index([1001], dtype='int64'),
 '21393': Int64Index([76], dtype='int64'),
 '21395': Int64Index([1173], dtype='int64'),
 '21423': Int64Index([668], dtype='int64'),
 '2148': Int64Index([537], dtype='int64'),
 '2150': Int64Index([116], dtype='int64'),
 '21519': Int64Index([546], dtype='int64'),
 '21524': Int64Index([154], dtype='int64'),
 '2158': Int64Index([859, 1136], dtype='int64'),
 '2159': Int64Index([799], dtype='int64'),
 '2160': Int64Index([1115], dtype='int64'),
 '2169': Int64Index([304], dtype='int64'),
 '2177': Int64Index([1095], dtype='int64'),
 '2186': Int64Index([333], dtype='int64'),
 '2189': Int64Index([266], dtype='int64'),
 '219': Int64Index([188, 246, 265], dtype='int64'),
 '2194': Int64Index([876], dtype='int64'),
 '2195': Int64Index([667, 698, 737], dtype='int64'),
 '2200': Int64Index([768], dtype='int64'),
 '2203': Int64Index([1197], dtype='int64'),
 '2207': Int64Index([919], dtype='int64'),
 '2215': Int64Index([582], dtype='int64'),
 '2218': Int64Index([267], dtype='int64'),
 '2228': Int64Index([993], dtype='int64'),
 '223': Int64Index([82, 94, 98, 99, 133, 134, 173], dtype='int64'),
 '2232': Int64Index([553, 838], dtype='int64'),
 '2236': Int64Index([1070], dtype='int64'),
 '2242': Int64Index([446], dtype='int64'),
 '2246': Int64Index([443], dtype='int64'),
 '2247': Int64Index([459], dtype='int64'),
 '225': Int64Index([35, 37, 41, 81], dtype='int64'),
 '2251': Int64Index([869], dtype='int64'),
 '2252': Int64Index([930], dtype='int64'),
 '2261': Int64Index([1069], dtype='int64'),
 '2263': Int64Index([620], dtype='int64'),
 '227': Int64Index([2, 4], dtype='int64'),
 '2273': Int64Index([1225], dtype='int64'),
 '2274': Int64Index([1177], dtype='int64'),
 '2280': Int64Index([226], dtype='int64'),
 '22825': Int64Index([1114], dtype='int64'),
 '2299': Int64Index([692, 703, 720], dtype='int64'),
 '2303': Int64Index([124], dtype='int64'),
 '2306': Int64Index([305], dtype='int64'),
 '23074': Int64Index([590], dtype='int64'),
 '2308': Int64Index([1210], dtype='int64'),
 '231': Int64Index([343], dtype='int64'),
 '2315': Int64Index([1190], dtype='int64'),
 '2316': Int64Index([486], dtype='int64'),
 '2319': Int64Index([260], dtype='int64'),
 '2336': Int64Index([1084], dtype='int64'),
 '2337': Int64Index([425, 502], dtype='int64'),
 '23413': Int64Index([507], dtype='int64'),
 '2345': Int64Index([1159], dtype='int64'),
 '2347': Int64Index([448, 1189], dtype='int64'),
 '2350': Int64Index([1124], dtype='int64'),
 '2353': Int64Index([1120, 1220], dtype='int64'),
 '2354': Int64Index([823], dtype='int64'),
 '2357': Int64Index([545], dtype='int64'),
 '2360': Int64Index([866], dtype='int64'),
 '23632': Int64Index([1036], dtype='int64'),
 '2365': Int64Index([858], dtype='int64'),
 '238': Int64Index([989], dtype='int64'),
 '2380': Int64Index([6], dtype='int64'),
 '239': Int64Index([430], dtype='int64'),
 '2403': Int64Index([696], dtype='int64'),
 '2408': Int64Index([854], dtype='int64'),
 '2410': Int64Index([976], dtype='int64'),
 '2416': Int64Index([1063], dtype='int64'),
 '2439': Int64Index([908], dtype='int64'),
 '244': Int64Index([106], dtype='int64'),
 '2440': Int64Index([821], dtype='int64'),
 '24403': Int64Index([1009], dtype='int64'),
 '2443': Int64Index([388], dtype='int64'),
 '2444': Int64Index([416], dtype='int64'),
 '2447': Int64Index([411], dtype='int64'),
 '2452': Int64Index([1152], dtype='int64'),
 '2454': Int64Index([366], dtype='int64'),
 '2459': Int64Index([463], dtype='int64'),
 '2460': Int64Index([1135], dtype='int64'),
 '2463': Int64Index([300], dtype='int64'),
 '2464': Int64Index([74], dtype='int64'),
 '2466': Int64Index([183], dtype='int64'),
 '2478': Int64Index([110], dtype='int64'),
 '2485': Int64Index([971], dtype='int64'),
 '24929': Int64Index([277], dtype='int64'),
 '2494': Int64Index([494], dtype='int64'),
 '2496': Int64Index([1223], dtype='int64'),
 '2497': Int64Index([986], dtype='int64'),
 '2499': Int64Index([407], dtype='int64'),
 '2509': Int64Index([653, 677], dtype='int64'),
 '2510': Int64Index([414], dtype='int64'),
 '2512': Int64Index([1081], dtype='int64'),
 '2523': Int64Index([303], dtype='int64'),
 '2527': Int64Index([360], dtype='int64'),
 '2528': Int64Index([1166], dtype='int64'),
 '2538': Int64Index([390], dtype='int64'),
 '2545': Int64Index([1066], dtype='int64'),
 '2551': Int64Index([596, 624], dtype='int64'),
 '2576': Int64Index([67], dtype='int64'),
 '25775': Int64Index([1016], dtype='int64'),
 '258': Int64Index([849], dtype='int64'),
 '2581': Int64Index([1140], dtype='int64'),
 '25945': Int64Index([569], dtype='int64'),
 '2596': Int64Index([759], dtype='int64'),
 '260': Int64Index([190], dtype='int64'),
 '26097': Int64Index([46], dtype='int64'),
 '2613': Int64Index([716, 719, 753], dtype='int64'),
 '2620': Int64Index([933], dtype='int64'),
 '26369': Int64Index([1045], dtype='int64'),
 '2638': Int64Index([1108], dtype='int64'),
 '2639': Int64Index([306], dtype='int64'),
 '264': Int64Index([533], dtype='int64'),
 '2648': Int64Index([374], dtype='int64'),
 '26529': Int64Index([962], dtype='int64'),
 '2659': Int64Index([616], dtype='int64'),
 '2679': Int64Index([180], dtype='int64'),
 '2680': Int64Index([1192], dtype='int64'),
 '2687': Int64Index([56], dtype='int64'),
 '2695': Int64Index([249], dtype='int64'),
 '2699': Int64Index([938], dtype='int64'),
 '2703': Int64Index([1202], dtype='int64'),
 '2709': Int64Index([1050], dtype='int64'),
 '2714': Int64Index([409], dtype='int64'),
 '273': Int64Index([354, 432], dtype='int64'),
 '2730': Int64Index([804], dtype='int64'),
 '2735': Int64Index([506], dtype='int64'),

In [20]:
import csv
f=open('metadata.csv','r',encoding='UTF-8')
rdr=csv.reader(f)

In [21]:
f.read()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 8278: invalid start byte

In [22]:
import pandas as pd

In [23]:
med_data=pd.read_csv('metadata.csv',encoding='CP949')

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 25815: illegal multibyte sequence